baseURL: "https://orbdb.io/"
theme: "up-business-theme"
languageCode: "en-us"

title: "ORB DB"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Orb DB"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  copyright: "© 2023 ORB DB Team"

  postProcess: false