baseURL: "https://orbdb.io/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Orb DB"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Orb DB"
  description: ""
  images: 
    - "images/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  copyright: "© 2023 Orb DB Team"

  postProcess: false